server:
  port: 0
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false
  cloud:
    gcp:
      storage:
        enabled: false
srv:
  captcha:
    enabled: false