# Spring Boot configuration
spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/img_srv_db
    username: dev
    password: letmein
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
# Logger configuration
logging:
  level:
    org.springframework: info
    org.hibernate: info
    org.springframework.orm.jpa: info
    org.springframework.transaction: info
    io.ulbrich: debug
# Server configuration
server:
  port: 8080

# Custom
srv:
  redis:
    url: redis://localhost:6379
  country-api:
    url: https://restcountries.eu/rest
