server:
  port: 8080
  error:
    include-stacktrace: always
spring:
  config:
    # https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.external-config.files.configtree
    import: "optional:file:./dev.yml"

srv:
  pg:
    host: localhost
    port: 5432
    database: img_srv_db
    username: dev
    password: letmein
  redis:
    url: redis://localhost:6379
  country-api:
    url: https://restcountries.eu/rest