version: "3.8"
services:
  postgres:
    ports:
      - "5555:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: letmein
    ports:
      - "5050:80"

  redis:
    ports:
      - "6379:6379"

  fake-gcs-server:
    ports:
      - "7071:8080"

  country-service-mock:
    ports:
      - "7072:8080"

  gcp-pubsub-emulator:
    ports:
      - "7073:8080"

volumes:
  pgdata: