---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: image-service
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
  name: image-service
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: image-service
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: image-service
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
  name: image-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: image-service
      app.kubernetes.io/version: 0.0.1-SNAPSHOT
  template:
    metadata:
      labels:
        app.kubernetes.io/name: image-service
        app.kubernetes.io/version: 0.0.1-SNAPSHOT
    spec:
      containers:
        - name: image-service
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: peterulb/image-service:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          volumeMounts:
            - name: app-config-map
              mountPath: /etc/config/properties
              readOnly: true
            - name: app-secret-properties
              mountPath: /etc/secrets/properties
              readOnly: true
            - name: app-gcp-key
              mountPath: /etc/secrets/key/gcp
              readOnly: true
      volumes:
        - name: app-config-map
          configMap:
            defaultMode: 384
            name: image-service-config
            optional: false
        - name: app-secret-properties
          secret:
            defaultMode: 384
            secretName: image-service-secret-properties
            optional: false
        - name: app-gcp-key
          secret:
            defaultMode: 384
            secretName: image-service-gcp-key
            optional: false
