kind: ConfigMap
apiVersion: v1
metadata:
  name: image-service-config
data:
  #  Why is project-id not inferred by the key? gcpProjectIdProvider.getProjectId() can be null for some reason
  application.yml: |-
    server:
      port: 8080
    srv:
      pg:
        host: localhost
        port: 5432
        database: img_srv_db
      gcp:
        project-id: project-id-string
        key-location: /etc/secrets/srv/gcp/key.json
      upload:
        bucket: bucket-string
        subscriptionName: subscription-string
        pool-size: 3
        queue-size: 100
      redis:
        url: redis://localhost:1234
      captcha:
        threshold: 0.5
        url: https://www.google.com/recaptcha/api
      country-api:
        url: https://country-api/rest
    logging:
      level:
        io.ulbrich: warn