---
kind: Secret
apiVersion: v1
metadata:
  name: image-service-secret-properties
type: Opaque
data:
  spring.datasource.username: USERBASE64
  spring.datasource.password: PASSWORDB64
---
kind: Secret
apiVersion: v1
metadata:
  name: image-service-gcp-key
data:
  gcp_key.json: KEYASBASE64