kind: Secret
apiVersion: v1
metadata:
  name: image-service-pg
type: Opaque
data:
  username: USERBASE64
  password: PASSWORDB64
---
kind: Secret
apiVersion: v1
metadata:
  name: image-service-gcp
data:
  key.json: KEYASBASE64